updated git scripts

diff --git a/scripts/gitclone b/scripts/gitclone
--- a/scripts/gitclone
+++ b/scripts/gitclone
@@ -1,11 +1,22 @@
-#!/bin/bash
-sshre='.*@(.*):[0-9]*\/?(.*)\/(.*)\.git'
-httpre='https?:\/\/(.*)\/(.*)\/(.*).git\/?'
-if [[ $1 =~ $sshre ]]; then
-	mkdir -p "$HOME"/git/"${BASH_REMATCH[1]}"
-	git clone "$1" "$HOME"/git/"${BASH_REMATCH[1]}"/"${BASH_REMATCH[2]}"
+#!/usr/bin/env bash
+
+url="$1"
+base="$HOME/git"
+
+if ! norm=$(git ls-remote --get-url "$url" 2>/dev/null); then
+  echo "Invalid Git repository URL"
+  return 1
 fi
-if [[ $1 =~ $httpre ]]; then
-	mkdir -p "$HOME"/git/"${BASH_REMATCH[1]}"
-	git clone "$1" "$HOME"/git/"${BASH_REMATCH[1]}"/"${BASH_REMATCH[2]}"
-fi
+
+norm="${norm#*://}"
+norm="${norm#*@}"
+norm="${norm/:/\/}"
+
+host="${norm%%/*}"
+path="${norm#*/}"
+path="${path%.git}"
+
+dest="$base/$host/$path"
+
+mkdir -p "$(dirname "$dest")"
+git clone "$url" "$dest"
